steps:
  - waitFor: [ '-' ]
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args: [ "./cloudbuild/retrieve_cache.sh" ]
    volumes:
      - name: caching.home
        path: /cachinghome
  - name: openjdk:11
    id: test
    entrypoint: "/bin/bash"
    args: [ "./cloudbuild/run_test.sh" ]
    volumes:
      - name: caching.home
        path: /cachinghome

  - name: openjdk:11
    id: build-image
    entrypoint: "/bin/bash"
    args: [ "./cloudbuild/build_image.sh" ]
    volumes:
      - name: caching.home
        path: /cachinghome
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor:
      - build-image
    id: "deploy"
    args:
      - 'run'
      - 'deploy'
      - "--image=gcr.io/$PROJECT_ID/livenotifications:$SHORT_SHA"
      - '--platform=managed'
      - '--project=$PROJECT_ID'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=768Mi'
      - '--min-instances=1'
      - '--set-env-vars=SPRING_PROFILES_ACTIVE=gcp,SPRING_REDIS_HOST=${_REDIS_HOST},SPRING_REDIS_PORT=${_REDIS_PORT}'
      - "--vpc-connector=${_VPC_CONNECTOR}"
      - 'livenotifications'
  - waitFor:
      - deploy
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args: [ "./cloudbuild/cache_files.sh" ]
    volumes:
      - name: caching.home
        path: /cachinghome
substitutions:
  _GCS_CACHE_BUCKET: <some bucket for caching gradle file>
  _GCS_CACHE_FILE: <file to hold cached content>
  _REDIS_HOST: "tobeprovided"
  _REDIS_PORT: "6379"
  _VPC_CONNECTOR: "tobeprovided"